spring.config.import: classpath:secret.properties

server:
  port: 8080

twilio:
  accountSid: ${twilio.accountSid}
  authToken: ${twilio.authToken}
  fromNumber: ${twilio.fromNumber}

openweather:
  url: https://api.openweathermap.org/data/2.5
  apiKey: ${openweather.apikey}